### ISSUE TITLE
Unresolvable peers in asia

### ISSUE THREAD

**Issue by r4sas** [yggdrasil-network/public-peers#129]
Peers operated by @Eninspace is not resolvable.
> * Hong Kong, operated by [Eninspace](https://github.com/Eninspace)
>   * `tcp://hongkong.eninspace.org:40004`
> * Tokyo, operated by [Eninspace](https://github.com/Eninspace)
>   * `tcp://tokyo.eninspace.org:40004`

**Comment by Eninspace** [comment]
I updated it, thanks
