### ISSUE TITLE
Good node is removed

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/public-peers#174]
Commit 50beea0c610ed66afbcb9bb427897bd8f906ae67 removes node `tcp://46.151.26.194:60575`.
I think it is wrong, node works fine from my location.
Please recheck it.

**Comment by Vort** [comment]
Fixed with 092c6e57b56695b223f441aa57792c4197775f71.

**Comment by neilalexander** [comment]
readded.

**Comment by neilalexander** [comment]
FYI https://publicpeers.neilalexander.dev is showing that this node went unreachable 3-4 hours ago again.

**Comment by Vort** [comment]
I will ask node operator about what is happened to node.

**Comment by Vort** [comment]
> Выключил, так как уехал их дома на выходные. Электроприборы выключил.
> Восстановлю в воскресенье вечером (время по мск)

He promises to get it back online tomorrow at evening.
