### ISSUE TITLE
List of v0.4 peers?

### ISSUE THREAD

**Issue by Chaz6** [yggdrasil-network/public-peers#253]
It would be useful to have a file listing v0.4 peers prior to the main release so that peers can be found sooner.

**Comment by Chaz6** [comment]
See also https://github.com/RiV-chain/public-peers.

**Comment by cathugger** [comment]
https://publicpeers.neilalexander.dev/ shows v0.4 and non-v0.4 peers with different highlight

**Comment by cwchristerw** [comment]
@neilalexander This issue can be closed
