### ISSUE TITLE
Finer regional granularity for the USA

### ISSUE THREAD

**Issue by ehmry** [yggdrasil-network/public-peers#340]
The USA is too large. The USA peers should be divided by nearest major city. I don't think the state system works very well, in any regard.

**Comment by ehmry** [comment]
Federal regions could also work, but few people know what those are https://en.wikipedia.org/wiki/List_of_regions_of_the_United_States#Standard_Federal_Regions

**Comment by ehmry** [comment]
This is also a concern with Germany, where one might be closer to Czechia than Hamburg or Munich.

**Comment by christoofar** [comment]
I went to look for hosts in UKR. 
[with the war busting the country's fixed-line system](https://hostpro.ua/blog/ua/activation-of-auto-suspend/) the only real datacenters that are OK for a VPS are in Odessa or Lviv.    Most of Kharkiv doesn't have power.

The best thing to do is to get on Telegram and tell Ukrainians how to get Yggdrasil installed locally and tell them to connect to the Netherlands.
