### ISSUE TITLE
Offline node: 78.27.153.163

### ISSUE THREAD

**Issue by marek22k** [yggdrasil-network/public-peers#365]
* Kiev, operated by [mvvpt](mvvpt0@bigmir.net)
  * `tcp://78.27.153.163:33165`
  * `tls://78.27.153.163:33166`
  * `tls://78.27.153.163:3785`
  * `tls://78.27.153.163:3784`
  * `tls://78.27.153.163:179`

contacted operator
sent email to mvvpt0@bigmir.net

**Comment by marek22k** [comment]
still in operation, but "it blocked until war has stopped."

**Comment by Saiv46** [comment]
@neilalexander Close this, node is still online
