### ISSUE TITLE
I'm clueless as to how I can make my VPS a public peer.

### ISSUE THREAD

**Issue by styromaniac** [yggdrasil-network/public-peers#394]
I have a VPS in Chicago through Vultr running Linux Mint Debian Edition. I'm hopeful to make it a public peer. How would I do that? Thanks in advance!

**Comment by neilalexander** [comment]
A public peer is basically an Yggdrasil node that can accept incoming peerings from other nodes, so in effect:

1. Make sure you have a listener set in the `Listen` section of your config, i.e. to make a TLS listener on port TCP/12345:
```
Listen: [
  tls://[::]:12345
]
```

2. Make sure that `AllowedPublicKeys` is **empty** in your config, as listing any keys in this setting would prevent your node from accepting incoming connections from unlisted nodes;

3. Make sure your firewall doesn't block incoming connections to that TCP port.

Then you can PR your connection string (following the example it would look like `tls://your-ip-address:12345`) to this repo if you like in the relevant file.

**Comment by styromaniac** [comment]
I have set the firewall to allow connections both ways on tcp port 8008 as well as set the listen value to tcp://149.28.123.138:8008 in /etc/yggdrasil.conf

For some odd reason, tcp://styromaniac.com:8008 was extremely slow, so that's why I just used the IPv4 address.
